---
title: "FT housing task"
author: "Paul King"
format: html
---

```{r}
#| label: setup
#| message: false
library(tidyverse)
library(readxl)
```

```{r}
#| label: read_data
prices <- 
  read_excel("/Users/arijitguchhait/Desktop/mydb/MA7441/Data/pp-2024_noAddr.xlsx") |>
  mutate(Price  = Price / 1e6)
```



```{r}
#| label: create_cumulative_frequency_plot

# Build a basic empirical cumulative distribution function 

plt <- 
  prices |>
  ggplot(aes(x = Price)) +
  stat_ecdf(geom = "line", colour = "steelblue", linewidth = 1, pad = FALSE)

#Set sensible x limits

plt <- 
 plt +
coord_cartesian(xlim = c(0, 1.4))

# Add title and axis labels

plt <- 
  plt +  labs(
    title = "UK house prices vary widely, with a quarter of sales priced below £183,000",
   subtitle = "England and Wales",
   x = "Price, 2024 (£mn)",
   y = "Cumulative % of all sales",
  caption = "Source HMLR" )

# Calculate position of vertical lines

quartiles <- quantile(prices$Price, c(0.25, 0.5, 0.75))

# # Add vertical lines
plt <- 
 plt + geom_vline(xintercept = quartiles)

# Change position of x and y tick marks and grid lines
# Change background and other colours
plt <- 
plt +
theme_minimal() +
theme(plot.background = element_rect(fill = "#EBD3DA"))
# Label vertical lines
```


```{r}
#| label: plot_it
plt
```
