---
title: "UK Road Safety: Collisions"
subtitle: "ods-team-01"
author: "Arijit Guchhait"
date: today
format:
  html:
    df-print: paged
    #code-fold: true
    theme: cosmo
  pdf: default
---
# 1. Data Wrangling
### 1.1 Load Package
```{r}
library(tidyverse)
library(dplyr)
```
### 1.2 Read the Data
```{r}
df <- read.csv("https://data.dft.gov.uk/road-accidents-safety-data/dft-road-casualty-statistics-collision-provisional-2025.csv")
```
### 1.3 Inspect the structure and display 5 rows
```{r}
str(df)
head(df,5)
```
# 1.4 Removing Missing Values
```{r}
if(any(colSums(is.na(df))>0)) df_clean <- na.omit(df) else df_clean <- df
```
# 1.5 Removing Dublicates
```{r}
df_clean=unique(df_clean)
```
# 1.6 Standarise Colums and Feature new month column
```{r}
df_clean <- df_clean %>% mutate(
  date=as.Date(date,format="%d/%m/%Y"),
  month=as.numeric(format(date,"%m")),
  hour <- as.integer(substr(time,1,2))
)
```
#Visulizations
### What proportion of collisions occur under different weather and light conditions?
```{r}
table(df_clean$weather_conditions)
table(df_clean$light_conditions)
df_clean$weather_conditions_labels <- factor(df_clean$weather_conditions,
                                      levels = c(1,2,3,4,5,6,7,8,9,-1),
                                      labels=c("fine",
                                               "raining",
                                               "snowing",
                                               "others",
                                               "others",
                                               "others",
                                               "others",
                                               "others",
                                               "others",
                                               "n/a"))
df_clean$light_conditions_labels <- factor(df_clean$light_conditions,
                                     levels = c(1,4,5,6,7,-1),
                                     labels=c("daylight",
                                              "darkness_with_lights",
                                              "darkness",
                                              "darkness",
                                              "darkness_unknown",
                                              "n/a"))
table(df_clean$weather_conditions_labels)  
table(df_clean$light_conditions_labels)
df_clean%>%
  filter(light_conditions_labels !='n/a' & weather_conditions_labels!='n/a') %>% 
  ggplot(aes(x = weather_conditions_labels, fill = light_conditions_labels)) + 
  geom_bar(position="fill")+scale_y_continuous(labels = scales::percent)+
  labs(x="Weather Condition",y="Proportion of Collisions",fill="Light Conditions",
       title="Weather and Light conditions for collisions")
```


